services:
  app:
    image: rusian/gitolite-cgit
    container_name: gitolite-cgit
    env_file: config.env
    volumes:
      - ssh:/etc/ssh
      - git:/var/lib/git
    ports:
      - 22:22
      - 80:80
      - 9418:9418
volumes:
  ssh:
  git:
