version: "3.9"

services:
  gitolite:
    image: ghcr.io/baddate/gitolite-cgit-docker-gitolite:latest
    container_name: gitolite
    restart: unless-stopped

    ports:
      - "2222:22" # SSH access

    volumes:
      - git-data:/var/lib/git # gitolite home
      - ssh-data:/etc/ssh # persistent host keys

    networks:
      - git-net

  cgit:
    image: ghcr.io/baddate/gitolite-cgit-docker-cgit:latest
    container_name: cgit
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/cache/nginx
      - /var/lib/nginx/logs

    ports:
      - "8080:80" # Web UI

    volumes:
      - git-data:/var/lib/git:ro # read-only mount

    depends_on:
      - gitolite

    networks:
      - git-net

volumes:
  git-data:
  ssh-data:

networks:
  git-net:
    driver: bridge
