#!/usr/bin/env python3
import markdown
import sys
sys.path.insert(0, "/usr/local/lib/cgit")

import io
from pygments.formatters import HtmlFormatter
from markdown.extensions.toc import TocExtension
from catppuccin_macchiato import CatppuccinMacchiatoStyle
from catppuccin_latte import CatppuccinLatteStyle

sys.stdin = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.stdout.write(HtmlFormatter(style=CatppuccinMacchiatoStyle, nobackground=True).get_style_defs('.highlight'))
sys.stdout.write('\n@media (prefers-color-scheme: light) {\n')
sys.stdout.write(HtmlFormatter(style=CatppuccinLatteStyle, nobackground=True).get_style_defs('.highlight'))
sys.stdout.write('\n}\n')
sys.stdout.write('''
</style>
''')
sys.stdout.write("<div class='markdown-body'>")
sys.stdout.flush()
# Note: you may want to run this through bleach for sanitization
markdown.markdownFromFile(
    output_format="html5",
    extensions=[
        "markdown.extensions.fenced_code",
        "markdown.extensions.codehilite",
        "markdown.extensions.tables",
        "markdown.extensions.admonition",
        "markdown.extensions.sane_lists",
        TocExtension(anchorlink=True)],
    extension_configs={
        "markdown.extensions.codehilite": {"css_class": "highlight"}})
sys.stdout.write("</div>")
