name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Validate and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic Version Validation
        id: validate_tag
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Checking tag: $TAG_NAME"

          SEMVER_REGEX="^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"

          if [[ ! $TAG_NAME =~ $SEMVER_REGEX ]]; then
            echo "::error::Tag '$TAG_NAME' does not follow Semantic Versioning (vX.Y.Z). Workflow failed."
            exit 1
          fi

          if [[ $TAG_NAME == *"-"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "Type: Pre-release"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "Type: Full Release"
          fi

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.validate_tag.outputs.is_prerelease }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
