name: release

on:
  schedule:
    - cron: 0 0 * * 5
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release-default:
    runs-on: ubuntu-latest
    steps:
      - name: Set short SHA
        id: short_sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: gitolite-cgit
          file: gitolite-cgit/Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/386
            linux/ppc64le
          push: false
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ steps.short_sha.outputs.sha_short }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os"
          severity: "CRITICAL,HIGH"
          cache: "false"

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: gitolite-cgit
          file: gitolite-cgit/Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/386
            linux/ppc64le
          push: true
          no-cache: false
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ steps.short_sha.outputs.sha_short }}
